// Mission command lists per firmware, as Mission Planner's planner offers them (logic 13).
// Generated 2026-10-05 from ~/MissionPlanner-latest/mavcmd.xml (the file FlightPlanner.readCMDXML reads)
// with the ids of MAVLink.dll's MAV_CMD enum. Order = MP's dropdown order. Columns P1..P4, X, Y, Z;
// "" = unused (MP shows a blank header). readCMDXML appends the unit to unitType alt/speed/dist and to
// a Z named "Alt"; the planner is SI (link B is), so that is always m or m/s here.
// Do not edit by hand: regenerate from MP's files.

export type CmdSet = 'APRover' | 'AC2' | 'APM';

/** [MP name, MAV_CMD id, [P1, P2, P3, P4, X, Y, Z] column names] */
export type CmdDef = readonly [string, number, readonly [string, string, string, string, string, string, string]];

export const MAVCMD: Record<CmdSet, readonly CmdDef[]> = {
  APRover: [
    ["WAYPOINT", 16, ["Delay", "", "", "", "Lat", "Long", "Alt (m)"]],
    ["RETURN_TO_LAUNCH", 20, ["", "", "", "", "", "", ""]],
    ["DELAY", 93, ["Seconds (or -1)", "Hour UTC (or -1)", "Minute UTC (or -1)", "Second UTC", "", "", ""]],
    ["GUIDED_ENABLE", 92, ["on=1/off=0", "", "", "", "", "", ""]],
    ["LOITER_UNLIM", 17, ["", "", "", "", "Lat", "Long", "Alt (m)"]],
    ["LOITER_TURNS", 18, ["Turns", "", "Radius", "", "Lat", "Long", "Alt (m)"]],
    ["LOITER_TIME", 19, ["Time s", "", "", "", "Lat", "Long", "Alt (m)"]],
    ["SCRIPT_TIME", 42702, ["command", "timeout", "arg1", "arg2", "arg3", "arg4", ""]],
    ["DO_SEND_SCRIPT_MESSAGE", 217, ["ID", "P1", "P2", "P3", "", "", ""]],
    ["SET_YAW_SPEED", 213, ["angle(CD)", "Speed(0..1)", "0=Abs,1=Rel", "", "", "", ""]],
    ["IMAGE_START_CAPTURE", 2000, ["Id", "Interval", "Total Images", "", "", "", ""]],
    ["IMAGE_STOP_CAPTURE", 2001, ["Id", "", "", "", "", "", ""]],
    ["SET_CAMERA_ZOOM", 531, ["Type", "Value", "", "", "", "", ""]],
    ["SET_CAMERA_FOCUS", 532, ["Type", "Value", "", "", "", "", ""]],
    ["SET_CAMERA_SOURCE", 534, ["Id", "Primary(1:RGB,2:IR,3:NDVI,4:Wide)", "Secondary(1:RGB,2:IR,3:NDVI,4:Wide)", "", "", "", ""]],
    ["VIDEO_START_CAPTURE", 2500, ["StreamId", "", "", "", "", "", ""]],
    ["VIDEO_STOP_CAPTURE", 2501, ["StreamId", "", "", "", "", "", ""]],
    ["DO_AUX_FUNCTION", 218, ["AuxFunction", "SwitchPosition", "", "", "", "", ""]],
    ["DO_CHANGE_SPEED", 178, ["", "Speed (m/s)", "", "", "", "", ""]],
    ["DO_DIGICAM_CONFIGURE", 202, ["Mode", "Shutter Speed", "Aperture", "ISO", "ExposureMode", "CommandID", ""]],
    ["DO_DIGICAM_CONTROL", 203, ["Session Control", "Zoom Position", "Zoom Step", "Focus Lock", "Shutter Cmd", "CommandID", ""]],
    ["DO_GIMBAL_MANAGER_PITCHYAW", 1000, ["Pitch Angle", "Yaw Angle", "Pitch Rate", "Yaw Rate", "Flags", "", "Gimbal Id"]],
    ["DO_GRIPPER", 211, ["Gripper No", "drop(0)/grab(1)", "", "", "", "", ""]],
    ["DO_JUMP", 177, ["WP #", "Repeat#", "", "", "", "", ""]],
    ["JUMP_TAG", 600, ["Tag", "", "", "", "", "", ""]],
    ["DO_JUMP_TAG", 601, ["Tag", "Repeat", "", "", "", "", ""]],
    ["DO_GUIDED_LIMITS", 222, ["timeout S", "", "", "max dist", "", "", ""]],
    ["DO_MOUNT_CONTROL", 205, ["Pitch", "Roll", "Yaw", "", "", "", ""]],
    ["DO_REPEAT_RELAY", 182, ["Relay No", "Repeat#", "Delay (s)", "", "", "", ""]],
    ["DO_REPEAT_SERVO", 184, ["Ser No", "PWM", "Repeat#", "Delay (s)", "", "", ""]],
    ["DO_SET_CAM_TRIGG_DIST", 206, ["Dist (m)", "", "", "", "", "", ""]],
    ["DO_SET_RELAY", 181, ["Relay No", "off(0)/on(1)", "", "", "", "", ""]],
    ["DO_SET_RESUME_REPEAT_DIST", 215, ["Distance(m)", "", "", "", "", "", ""]],
    ["DO_SET_REVERSE", 194, ["Direction (0=F,1=R)", "", "", "", "", "", ""]],
    ["DO_SET_HOME", 179, ["Current(1)/Spec(0)", "", "", "", "Lat", "Long", "Alt (m)"]],
    ["DO_SET_ROI", 201, ["", "", "", "", "Lat", "Long", "Alt (m)"]],
    ["DO_SET_ROI_LOCATION", 195, ["Gimbal Id", "", "", "", "Lat", "Long", "Alt (m)"]],
    ["DO_SET_ROI_NONE", 197, ["Gimbal Id", "", "", "", "", "", ""]],
    ["DO_SET_SERVO", 183, ["Ser No", "PWM", "", "", "", "", ""]],
    ["DO_SPRAYER", 216, ["Sprayer Enable", "", "", "", "", "", ""]],
    ["CONDITION_DELAY", 112, ["Time (sec)", "", "", "", "", "", ""]],
    ["CONDITION_DISTANCE", 114, ["Dist (m)", "", "", "", "", "", ""]],
  ],
  AC2: [
    ["WAYPOINT", 16, ["Delay", "", "", "", "Lat", "Long", "Alt (m)"]],
    ["TAKEOFF", 22, ["", "", "", "", "", "", "Alt (m)"]],
    ["RETURN_TO_LAUNCH", 20, ["", "", "", "", "", "", ""]],
    ["ATTITUDE_TIME", 42703, ["Time (sec)", "Roll", "Pitch", "Yaw", "ClimbRate", "", ""]],
    ["DELAY", 93, ["Seconds (or -1)", "Hour UTC (or -1)", "Minute UTC (or -1)", "Second UTC", "", "", ""]],
    ["GUIDED_ENABLE", 92, ["on=1/off=0", "", "", "", "", "", ""]],
    ["LAND", 21, ["", "", "", "", "Lat", "Long", "Alt (m)"]],
    ["LOITER_TIME", 19, ["Time s", "", "", "", "Lat", "Long", "Alt (m)"]],
    ["LOITER_TURNS", 18, ["Turns", "", "Radius", "", "Lat", "Long", "Alt (m)"]],
    ["LOITER_UNLIM", 17, ["", "", "", "", "Lat", "Long", "Alt (m)"]],
    ["PAYLOAD_PLACE", 94, ["max descent", "", "", "", "Lat", "Long", "Alt (m)"]],
    ["SCRIPT_TIME", 42702, ["command", "timeout", "arg1", "arg2", "arg3", "arg4", ""]],
    ["DO_SEND_SCRIPT_MESSAGE", 217, ["ID", "P1", "P2", "P3", "", "", ""]],
    ["SPLINE_WAYPOINT", 82, ["Delay", "", "", "", "Lat", "Long", "Alt (m)"]],
    ["IMAGE_START_CAPTURE", 2000, ["Id", "Interval", "Total Images", "", "", "", ""]],
    ["IMAGE_STOP_CAPTURE", 2001, ["Id", "", "", "", "", "", ""]],
    ["SET_CAMERA_ZOOM", 531, ["Type", "Value", "", "", "", "", ""]],
    ["SET_CAMERA_FOCUS", 532, ["Type", "Value", "", "", "", "", ""]],
    ["SET_CAMERA_SOURCE", 534, ["Id", "Primary(1:RGB,2:IR,3:NDVI,4:Wide)", "Secondary(1:RGB,2:IR,3:NDVI,4:Wide)", "", "", "", ""]],
    ["VIDEO_START_CAPTURE", 2500, ["StreamId", "", "", "", "", "", ""]],
    ["VIDEO_STOP_CAPTURE", 2501, ["StreamId", "", "", "", "", "", ""]],
    ["DO_AUX_FUNCTION", 218, ["AuxFunction", "SwitchPosition", "", "", "", "", ""]],
    ["DO_CHANGE_SPEED", 178, ["Type (0:horiz,2:up,3:down)", "Speed m/s", "", "", "", "", ""]],
    ["DO_DIGICAM_CONFIGURE", 202, ["Mode", "Shutter Speed", "Aperture", "ISO", "ExposureMode", "CommandID", ""]],
    ["DO_DIGICAM_CONTROL", 203, ["Session Control", "Zoom Position", "Zoom Step", "Focus Lock", "Shutter Cmd", "CommandID", ""]],
    ["DO_ENGINE_CONTROL", 223, ["Start Engine", "Cold Start", "Height Delay", "", "", "", ""]],
    ["DO_GIMBAL_MANAGER_PITCHYAW", 1000, ["Pitch Angle", "Yaw Angle", "Pitch Rate", "Yaw Rate", "Flags", "", "Gimbal Id"]],
    ["DO_GRIPPER", 211, ["Gripper No", "drop(0)/grab(1)", "", "", "", "", ""]],
    ["DO_GUIDED_LIMITS", 222, ["timeout S", "min alt", "max alt", "max dist", "", "", ""]],
    ["DO_JUMP", 177, ["WP #", "Repeat#", "", "", "", "", ""]],
    ["JUMP_TAG", 600, ["Tag", "", "", "", "", "", ""]],
    ["DO_JUMP_TAG", 601, ["Tag", "Repeat", "", "", "", "", ""]],
    ["DO_LAND_START", 189, ["", "", "", "", "", "", ""]],
    ["DO_MOUNT_CONTROL", 205, ["Pitch", "Roll", "Yaw", "", "", "", ""]],
    ["DO_PARACHUTE", 208, ["Enable(1)/Release(2)", "", "", "", "", "", ""]],
    ["DO_REPEAT_RELAY", 182, ["Relay No", "Repeat#", "Delay (s)", "", "", "", ""]],
    ["DO_REPEAT_SERVO", 184, ["Ser No", "PWM", "Repeat#", "Delay (s)", "", "", ""]],
    ["DO_SET_CAM_TRIGG_DIST", 206, ["Dist (m)", "", "", "", "", "", ""]],
    ["DO_SET_HOME", 179, ["Current(1)/Spec(0)", "", "", "", "Lat", "Long", "Alt (m)"]],
    ["DO_SET_RELAY", 181, ["Relay No", "off(0)/on(1)", "", "", "", "", ""]],
    ["DO_SET_RESUME_REPEAT_DIST", 215, ["Distance(m)", "", "", "", "", "", ""]],
    ["DO_SET_ROI", 201, ["", "", "", "", "Lat", "Long", "Alt (m)"]],
    ["DO_SET_ROI_LOCATION", 195, ["Gimbal Id", "", "", "", "Lat", "Long", "Alt (m)"]],
    ["DO_SET_ROI_NONE", 197, ["Gimbal Id", "", "", "", "", "", ""]],
    ["DO_SET_SERVO", 183, ["Ser No", "PWM", "", "", "", "", ""]],
    ["DO_SPRAYER", 216, ["Sprayer Enable", "", "", "", "", "", ""]],
    ["DO_WINCH", 42600, ["winch no", "action", "length", "rate", "", "", ""]],
    ["CONDITION_DELAY", 112, ["Time (sec)", "", "", "", "", "", ""]],
    ["CONDITION_DISTANCE", 114, ["Dist (m)", "", "", "", "", "", ""]],
    ["CONDITION_YAW", 115, ["Deg", "Speed deg/s", "Dir 1=CW", "0=Abs,1=Rel", "", "", ""]],
  ],
  APM: [
    ["WAYPOINT", 16, ["", "Acc radius", "Pass by dist", "", "Lat", "Long", "Alt (m)"]],
    ["LOITER_UNLIM", 17, ["", "", "Dir 1=CW", "", "Lat", "Long", "Alt (m)"]],
    ["LOITER_TURNS", 18, ["Turns", "", "Radius", "1=Exit Tangent", "Lat", "Long", "Alt (m)"]],
    ["LOITER_TIME", 19, ["Time s", "", "Dir 1=CW", "1=Exit Tangent", "Lat", "Long", "Alt (m)"]],
    ["LOITER_TO_ALT", 31, ["Radius", "", "", "", "Lat", "Long", "Alt (m)"]],
    ["RETURN_TO_LAUNCH", 20, ["", "", "", "", "", "", ""]],
    ["LAND", 21, ["Abort Alt", "", "", "", "Lat", "Long", "Alt (m)"]],
    ["TAKEOFF", 22, ["Pitch Angle", "", "", "", "", "", "Alt (m)"]],
    ["DELAY", 93, ["Seconds (or -1)", "Hour UTC (or -1)", "Minute UTC (or -1)", "Second UTC", "", "", ""]],
    ["VTOL_TAKEOFF", 84, ["", "", "", "", "", "", "Alt (m)"]],
    ["VTOL_LAND", 85, ["", "", "", "", "Lat", "Long", "Alt (m)"]],
    ["PAYLOAD_PLACE", 94, ["max descent", "", "", "", "Lat", "Long", "Alt (m)"]],
    ["SCRIPT_TIME", 42702, ["commandId", "timeout", "arg1", "arg2", "arg3", "arg4", ""]],
    ["DO_SEND_SCRIPT_MESSAGE", 217, ["ID", "P1", "P2", "P3", "", "", ""]],
    ["DO_VTOL_TRANSITION", 3000, ["mode (3=mc/4=plane)", "", "", "", "", "", ""]],
    ["IMAGE_START_CAPTURE", 2000, ["Id", "Interval", "Total Images", "", "", "", ""]],
    ["IMAGE_STOP_CAPTURE", 2001, ["Id", "", "", "", "", "", ""]],
    ["SET_CAMERA_ZOOM", 531, ["Type", "Value", "", "", "", "", ""]],
    ["SET_CAMERA_FOCUS", 532, ["Type", "Value", "", "", "", "", ""]],
    ["SET_CAMERA_SOURCE", 534, ["Id", "Primary(1:RGB,2:IR,3:NDVI,4:Wide)", "Secondary(1:RGB,2:IR,3:NDVI,4:Wide)", "", "", "", ""]],
    ["VIDEO_START_CAPTURE", 2500, ["StreamId", "", "", "", "", "", ""]],
    ["VIDEO_STOP_CAPTURE", 2501, ["StreamId", "", "", "", "", "", ""]],
    ["DO_AUX_FUNCTION", 218, ["AuxFunction", "SwitchPosition", "", "", "", "", ""]],
    ["ALTITUDE_WAIT", 83, ["Alt", "Descent rate", "Wiggle time", "", "", "", ""]],
    ["CONTINUE_AND_CHANGE_ALT", 30, ["", "", "", "", "", "", "Alt (m)"]],
    ["CONDITION_DELAY", 112, ["Time (sec)", "", "", "", "", "", ""]],
    ["CONDITION_DISTANCE", 114, ["Dist (m)", "", "", "", "", "", ""]],
    ["CONDITION_YAW", 115, ["", "", "", "", "", "", ""]],
    ["DO_GRIPPER", 211, ["Gripper No", "drop(0)/grab(1)", "", "", "", "", ""]],
    ["DO_LAND_START", 189, ["", "", "", "", "Lat", "Long", ""]],
    ["DO_SET_ROI", 201, ["", "", "", "", "Lat", "Long", "Alt (m)"]],
    ["DO_SET_ROI_LOCATION", 195, ["Gimbal Id", "", "", "", "Lat", "Long", "Alt (m)"]],
    ["DO_SET_ROI_NONE", 197, ["Gimbal Id", "", "", "", "", "", ""]],
    ["DO_INVERTED_FLIGHT", 210, ["0=normal, 1=inverted", "", "", "", "", "", ""]],
    ["DO_SET_CAM_TRIGG_DIST", 206, ["Dist (m)", "", "", "", "", "", ""]],
    ["DO_JUMP", 177, ["WP #", "Repeat#", "", "", "", "", ""]],
    ["JUMP_TAG", 600, ["Tag", "", "", "", "", "", ""]],
    ["DO_JUMP_TAG", 601, ["Tag", "Repeat", "", "", "", "", ""]],
    ["DO_CHANGE_SPEED", 178, ["Type (0=as 1=gs)", "Speed (m/s)", "Throttle(%)", "", "", "", ""]],
    ["DO_SET_HOME", 179, ["Current(1)/Spec(0)", "", "", "", "Lat", "Long", "Alt (m)"]],
    ["DO_SET_RELAY", 181, ["Relay No", "off(0)/on(1)", "", "", "", "", ""]],
    ["DO_REPEAT_RELAY", 182, ["Relay No", "Repeat#", "Delay (s)", "", "", "", ""]],
    ["DO_SET_SERVO", 183, ["Ser No", "PWM", "", "", "", "", ""]],
    ["DO_REPEAT_SERVO", 184, ["Ser No", "PWM", "Repeat#", "Delay (s)", "", "", ""]],
    ["DO_DIGICAM_CONFIGURE", 202, ["Mode", "Shutter Speed", "Aperture", "ISO", "ExposureMode", "CommandID", ""]],
    ["DO_DIGICAM_CONTROL", 203, ["Session Control", "Zoom Position", "Zoom Step", "Focus Lock", "Shutter Cmd", "CommandID", ""]],
    ["DO_MOUNT_CONTROL", 205, ["Pitch", "Roll", "Yaw", "", "", "", ""]],
    ["DO_GIMBAL_MANAGER_PITCHYAW", 1000, ["Pitch Angle", "Yaw Angle", "Pitch Rate", "Yaw Rate", "Flags", "", "Gimbal Id"]],
    ["DO_PARACHUTE", 208, ["Enable(1)/Release(2)", "", "", "", "", "", ""]],
    ["DO_FENCE_ENABLE", 207, ["Disable(0)/Enable(1)/Disable Floor Only(2)", "", "", "", "", "", ""]],
    ["DO_SPRAYER", 216, ["Sprayer Enable", "", "", "", "", "", ""]],
    ["DO_AUTOTUNE_ENABLE", 212, ["enable", "", "", "", "", "", ""]],
    ["DO_ENGINE_CONTROL", 223, ["Start Engine", "Cold Start", "Height Delay", "", "", "", ""]],
    ["DO_SET_RESUME_REPEAT_DIST", 215, ["Distance(m)", "", "", "", "", "", ""]],
  ],
};
